export const QUESTIONS_ACTION_TYPES = {
  QUESTIONS_LIST_REQUEST: "QUESTIONS_LIST_REQUEST",
  QUESTIONS_LIST_SUCCESS: "QUESTIONS_LIST_SUCCESS",
  QUESTIONS_LIST_FAIL: "QUESTIONS_LIST_FAIL",
  QUESTIONS_LIST_UPDATE_ONE: "QUESTIONS_LIST_UPDATE_ONE",
};
